name = "BlockAverage"
uuid = "83ccec75-4b2a-4217-b72b-3a6c241f5d0c"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
